// <auto-generated />
using DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(PizzeriaDbContext))]
    [Migration("20240221171959_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAccess.Data.Entities.Pizza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Pizzas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Good!",
                            Name = "Margherita",
                            Price = 10m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Good!",
                            Name = "Pepperoni",
                            Price = 12m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Cool!",
                            Name = "Hawaiian",
                            Price = 11m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Very good!",
                            Name = "Meat Lover's",
                            Price = 13m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Very good!",
                            Name = "Veggie Supreme",
                            Price = 11m
                        },
                        new
                        {
                            Id = 6,
                            Description = "Good!",
                            Name = "BBQ Chicken",
                            Price = 12m
                        },
                        new
                        {
                            Id = 7,
                            Description = "Very good!",
                            Name = "Supreme",
                            Price = 10m
                        },
                        new
                        {
                            Id = 8,
                            Description = "Good!",
                            Name = "Cheese Lover's",
                            Price = 11m
                        },
                        new
                        {
                            Id = 9,
                            Description = "Cool!",
                            Name = "Buffalo Chicken",
                            Price = 12m
                        },
                        new
                        {
                            Id = 10,
                            Description = "Cool!",
                            Name = "Mediterranean",
                            Price = 13m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
